# Full Example: https://github.com/geekan/MetaGPT/blob/main/config/config2.example.yaml
# Reflected Code: https://github.com/geekan/MetaGPT/blob/main/metagpt/config2.py
# Config Docs: https://docs.deepwisdom.ai/main/en/guide/get_started/configuration.html
llm:
  api_type: "codestallation" # or azure / ollama / groq etc.
  model: "deepseek" # or gpt-3.5-turbo
  base_url: "http://localhost:8000/v1" # or forward url / other llm url
